export const config = {
	ERROR: {
		QUERY_PARAMS: {
			INVALID_DOCUMENT: "Invalid Document",
			INVALID_PAGINATION: "Invalid Pagination",
			INVALID_COUNT: "Invalid Count",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			INVALID_ORDER: "Invalid order parameter",
			INVALID_POPULATE: "Invalid populate parameter",
			INVALID_SORT: "Invalid sort parameter",
			INVALID_QUERY: "Invalid Query",
			MISSING_ID: "ID is required",
			INVALID_FILTER: "Invalid folter format",
			INVALID_COMBINATION: "Invalid Combination",
			INVALID_ID: "Invalid ID",
		},
		USER: {
			NOT_FOUND: "User not found",
			INVALID_ID: "Invalid user ID",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_USER: "Error getting user",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update user",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			INVALID_EMAIL: "Invalid email format",
			EMAIL_ALREADY_EXISTS: "Email already exists",
			EMAIL_ALREADY_IN_USED: "Email already in use",
			ERROR_UPDATING_USER: "Error updating user",
			ERROR_DELETING_USER: "Error deleting user",
			INVALID_USER_ID_FORMAT: "Invalid user ID format",
			INVALID_FIELDS_PARAMETER: "Invalid fields parameter",
			INVALID_QUERY_PARAMETERS: "Invalid query parameters",
			INVALID_UPDATE_DATA: "Invalid update data",
			REQUEST_BODY_EMPTY: "Request body cannot be empty",
			VALIDATION_FAILED: "Validation failed",
			FIRST_NAME_REQUIRED: "First name is required",
			LAST_NAME_REQUIRED: "Last name is required",
			UNAUTHORIZED_USER_ID_NOT_FOUND: "Unauthorized - User ID not found",
			ERROR_DURING_USER_CREATION: "Error during user creation",
			FAILED_TO_CREATE_OR_FIND_PERSON: "Failed to create or find person",
			UPLOADING_AVATAR: "Uploading avatar for user",
			AVATAR_UPLOADED: "Avatar uploaded successfully",
			ORGANIZATION_VERIFIED: "Organization verified",
			USER_ALREADY_EXISTS: "User already exists",
			MISSING_REQUIRED_FIELDS: "Missing Required Fields",
			PERSON_NOT_FOUND: "Person not found",
		},
		PERSON: {
			NOT_FOUND: "Person not found",
			INVALID_ID: "Invalid person ID",
			MISSING_ID: "Missing person ID",
			USER_ID_REQUIRED: "Person ID is required",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_USER: "Error getting person",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update person",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			INVALID_EMAIL: "Invalid email format",
			EMAIL_ALREADY_EXISTS: "Email already exists",
			EMAIL_ALREADY_IN_USED: "Email already in use",
			ERROR_UPDATING_USER: "Error updating person",
			ERROR_DELETING_USER: "Error deleting person",
			GETTING_ALL_USERS: "Getting all persons",
		},
		IMAGE: {
			NO_IMAGE_PROVIDED: "No image provided",
			UPLOAD_FAILED: "Image upload failed",
			PUBLIC_ID_REQUIRED: "Public ID is required",
			NOT_FOUND: "Image not found",
			DELETE_FAILED: "Image deletion failed",
			PUBLIC_IDS_REQUIRED: "Public IDs are required",
			TRANSFORM_FAILED: "Image transformation failed",
		},
		AUTH: {
			UNAUTHORIZED: "Unauthorized",
			INVALID_TOKEN: "Invalid token",
			REGISTRATION_VALIDATION_FAILED: "Registration validation failed",
			LOGIN_VALIDATION_FAILED: "Login validation failed",
			PASSWORD_UPDATE_VALIDATION_FAILED: "Password update validation failed",
			FIRST_NAME_LAST_NAME_REQUIRED: "First name and last name are required",
			INVALID_ORGANIZATION_ID_FORMAT: "Invalid organization ID format",
			ORGANIZATION_NOT_FOUND: "Organization not found",
			USER_ALREADY_EXISTS: "User already exists",
			ERROR_DURING_REGISTRATION: "Error during registration",
			INVALID_CREDENTIALS: "Invalid credentials",
			ERROR_DURING_LOGIN: "Error during login",
			USER_ID_PASSWORD_REQUIRED: "User ID and new password are required",
			PASSWORD_MIN_LENGTH: "Password must be at least 6 characters long",
			ERROR_UPDATING_PASSWORD: "Error updating password",
			USER_NOT_FOUND: "User not found",
			REGISTRATION_SUCCESSFUL: "Registration successful",
			LOGGED_IN_SUCCESSFULLY: "Logged in successfully",
			PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully",
			FAILED_TO_CREATE_OR_FIND_PERSON: "Failed to create or find person",
			ORGANIZATION_VERIFIED: "Organization verified",
			TOKEN_GENERATED: "Token generated successfully",
			USER_LOGGED_IN: "User logged in successfully",
			ERROR_DURING_LOGOUT: "Error logging out",
		},
		ORGANIZATION: {
			MISSING_ID: "Missing organization ID",
			ORG_ID_REQUIRED: "Organization ID is required",
			INVALID_POPULATE: "Invalid populate value",
			POPULATE_MUST_BE_STRING: "Populate must be a string",
			NOT_FOUND: "Organization not found",
			INVALID_PAGE: "Invalid page value",
			INVALID_LIMIT: "Invalid limit value",
			INVALID_ORDER: "Invalid order value",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either asc or desc",
			INVALID_SORT: "Invalid sort value",
			SORT_MUST_BE_STRING: "Sort must be a string",
			NO_UPDATE_FIELDS: "No update fields provided",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field must be provided",
			ERROR_GETTING: "Error retrieving organization(s)",
			ERROR_UPDATING: "Error updating organization",
			ERROR_DELETING: "Error deleting organization",
			INVALID_INPUT: "Invalid input: name and code are required",
		},
		ROLE: {
			MISSING_ID: "Missing role ID",
			ROLE_ID_REQUIRED: "Role ID is required",
			NOT_FOUND: "Role not found",
			INVALID_PAGE: "Invalid page value",
			INVALID_LIMIT: "Invalid limit value",
			INVALID_ORDER: "Invalid order value",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either asc or desc",
			INVALID_SORT: "Invalid sort value",
			SORT_MUST_BE_STRING: "Sort must be a string",
			NO_UPDATE_FIELDS: "No update fields provided",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field must be provided",
			ERROR_GETTING: "Error retrieving role(s)",
			ERROR_CREATING: "Error creating role",
			ERROR_UPDATING: "Error updating role",
			ERROR_DELETING: "Error deleting role",
			INTERNAL_SERVER_ERROR: "Internal server error",
			INVALID_INPUT: "Invalid input: role name is required",
		},
		APP: {
			MISSING_ID: "Missing app ID",
			APP_ID_REQUIRED: "App ID is required",
			NOT_FOUND: "App not found",
			INVALID_PAGE: "Invalid page value",
			INVALID_LIMIT: "Invalid limit value",
			INVALID_ORDER: "Invalid order value",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either asc or desc",
			INVALID_SORT: "Invalid sort value",
			SORT_MUST_BE_STRING: "Sort must be a string",
			NO_UPDATE_FIELDS: "No update fields provided",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field must be provided",
			ERROR_GETTING: "Error retrieving app(s)",
			ERROR_CREATING: "Error creating app",
			ERROR_UPDATING: "Error updating app",
			ERROR_DELETING: "Error deleting app",
			INTERNAL_SERVER_ERROR: "Internal server error",
			INVALID_INPUT: "Invalid input: app name is required",
			CODE_EXISTS: "App code already exists",
		},
		PERMISSION: {
			MISSING_ID: "Permission ID is required",
			PERMISSION_ID_REQUIRED: "Permission ID is required",
			NOT_FOUND: "Permission not found",
			INVALID_INPUT: "Invalid input data",
			INTERNAL_SERVER_ERROR: "Internal server error while processing permission",
			ERROR_GETTING: "Error getting permission",
			ERROR_CREATING: "Error creating permission",
			ERROR_UPDATING: "Error updating permission",
			ERROR_DELETING: "Error deleting permission",
			ERROR_CHECKING: "Error checking permissions",
			INVALID_PAGE: "Invalid page parameter",
			INVALID_LIMIT: "Invalid limit parameter",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be 'asc' or 'desc'",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate must be a string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort must be a string",
			NO_UPDATE_FIELDS: "No fields to update",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required to update",
			MISSING_PARAMS: "Missing required parameters",
			ACCESS_POLICY_NOT_FOUND: "Access policy not found",
			ROLE_NOT_FOUND: "Role not found",
			DUPLICATE_PERMISSION: "Permission already exists for this access policy and role",
		},
		ACCESS_POLICY: {
			NOT_FOUND: "Access Policy not found",
			ERROR_GETTING: "Error getting Access Policy",
			NAME_EXISTS: "Access Policy name already exist",
			ERROR_UPDATING: "Error updating Access Policy",
			DELETED: "There has been an error deleting access policy",
		},
		COMMON: {
			INTERNAL_SERVER_ERROR: "Internal server error",
			NO_UPDATE_FIELDS: "Please include at least one field to update",
		},
	},

	SUCCESS: {
		USER: {
			RETRIEVED: "User retrieved successfully",
			DELETED: "User deleted",
			SOFT_DELETING: "Soft deleting user",
			UPDATE: "User updated",
			CREATED: "User created",
			LOGGED_IN: "User logged in",
			GETTING_USER_BY_ID: "Getting user by ID",
			GETTING_ALL_USERS: "Getting all users",
			LOGOUT_SUCCESSFUL: "Logout successful",
			PASSWORD_RESET_EMAIL_SENT: "Password reset email sent",
			PASSWORD_RESET_SUCCESSFUL: "Password reset successful",
			USER_UPDATED_SUCCESSFULLY: "User updated successfully",
			USERS_RETRIEVED_SUCCESSFULLY: "Users retrieved successfully",
			CURRENT_USER_RETRIEVED_SUCCESSFULLY: "Current user retrieved successfully",
			USER_CREATED_SUCCESSFULLY: "User created successfully",
		},
		AUTH: {
			REGISTRATION_SUCCESSFUL: "Registration successful",
			LOGGED_IN_SUCCESSFULLY: "Logged in successfully",
			PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully",
			USER_CREATED: "User created successfully",
			TOKEN_GENERATED: "Token generated successfully",
			ORGANIZATION_VERIFIED: "Organization verified successfully",
			USER_LOGGED_IN: "User logged in successfully",
			LOGGED_OUT_SUCCESSFULLY: "User logged out successfully",
		},
		PERSON: {
			RETRIEVED: "Person retrieved",
			DELETED: "Person deleted",
			SOFT_DELETING: "Soft deleting user",
			UPDATE: "Person updated",
			CREATED: "Person created",
			LOGGED_IN: "Person logged in",
			GETTING_USER_BY_ID: "Getting person by ID",
			GETTING_ALL_USERS: "Getting all persons",
		},
		IMAGE: {
			UPLOADED: "Image uploaded successfully",
			MULTIPLE_UPLOADED: "images uploaded successfully",
			DELETED: "Image deleted successfully",
			DELETION_COMPLETED: "Deletion completed",
			TRANSFORMED: "Image transformed successfully",
		},
		ORGANIZATION: {
			GETTING_BY_ID: "Getting organization by ID",
			RETRIEVED: "Organization retrieved successfully",
			GETTING_ALL: "Getting all organizations",
			CREATED: "Organization created successfully",
			UPDATED: "Organization updated successfully",
			SOFT_DELETING: "Soft deleting organization",
			DELETED: "Organization deleted successfully",
		},
		ROLE: {
			GETTING_BY_ID: "Getting role by ID",
			RETRIEVED: "Role retrieved successfully",
			GETTING_ALL: "Getting all roles",
			CREATED: "Role created successfully",
			UPDATED: "Role updated successfully",
			SOFT_DELETING: "Soft deleting role",
			DELETED: "Role deleted successfully",
		},
		APP: {
			GETTING_BY_ID: "Getting app by ID",
			RETRIEVED: "App retrieved successfully",
			GETTING_ALL: "Getting all apps",
			CREATED: "App created successfully",
			UPDATED: "App updated successfully",
			SOFT_DELETING: "Soft deleting app",
			DELETED: "App deleted successfully",
		},
		PERMISSION: {
			GETTING_BY_ID: "Getting permission by ID",
			RETRIEVED: "Permission retrieved successfully",
			GETTING_ALL: "Getting all permissions",
			CREATED: "Permission created successfully",
			UPDATED: "Permission updated successfully",
			DELETED: "Permission deleted successfully",
			DELETING: "Deleting permission",
			CHECKED: "Permission check completed successfully",
			UPDATE: "Permission updated successfully",
		},
		ACCESS_POLICY: {
			GETTING_BY_ID: "Success getting Access Policy by id",
			RETRIEVED: "Access Policy retrieved successfully",
			GETTING_ALL: "Success getting all Access Policy",
			CREATED: "Created Access Policy successfully",
			UPDATED: "Access Policy updated successfully",
			DELETED: "Access Policy deleted successfully",
		},
	},
	INFO: {
		USER: {
			REGISTERING_USER: "Registering user with email:",
			CREATING_USER_WITH_PERSON_ID: "Creating user with personId:",
			LOGGING_IN_USER: "Logging in user with email:",
		},
	},
	COMMON: {
		// Common field names
		ID: "id",
		EMAIL: "email",
		FIRST_NAME: "firstName",
		LAST_NAME: "lastName",
		ORGANIZATION_ID: "organizationId",
		USER_ID: "userId",
		BODY: "body",
		FIELDS: "fields",
		// Common resource names
		USER: "User",
		ORGANIZATION: "Organization",
		// Common values
		USERS: "users",
		AVATARS: "avatars",
		AUTO: "auto",
		AVATAR: "avatar",
		EMAIL_METHOD: "email",
		// HTTP methods
		GET: "GET",
		POST: "POST",
		PUT: "PUT",
		DELETE: "DELETE",
		PATCH: "PATCH",
		LOCK: "lock",
		// Common parameters
		START_DATE: "startDate",
		END_DATE: "endDate",
		ORDER_BY: "orderBy",
		DESC: "desc",
		// Common error codes
		UNAUTHORIZED: "UNAUTHORIZED",
		INTERNAL_SERVER_ERROR: "Internal server error",
		// Cookie settings
		TOKEN: "token",
		NONE: "none",
		LAX: "lax",
		PRODUCTION: "production",
	},
	ACTION: {
		CREATE: "create",
		READ: "read",
		UPDATE: "update",
		DELETE: "delete",
		CUSTOM: "custom",
	},
};
